CURDIR="$(dirname "$0")"

( set -e

echo "Building PLX in ${PLX:?}"

CURDIR="$(dirname "$0")"

. "$CURDIR/utils.sh"

if ! id "plx" &>/dev/null; then
    $CURDIR/setup-user.sh
fi

$CURDIR/create.sh
sudo -u plx $CURDIR/build-xtools.sh

echo "Completing filesystem..."

chown -R root:root $PLX/{usr,lib,var,etc,bin,sbin,tools,lib64}
mkdir -pv $PLX/{dev,proc,sys,run}
mknod -m 600 $PLX/dev/console c 5 1 || echo "console exists"
mknod -m 666 $PLX/dev/null c 1 3 || echo "devnull exists"
echo "nameserver 8.8.8.8" > $PLX/etc/resolv.conf

$CURDIR/vmount.sh

cp $CURDIR/chroot_utils.sh $PLX/build/src/
cp $CURDIR/utils.sh $PLX/build/src/

do_chroot_build() { (set -e
    CMD=". /build/src/utils.sh && . /build/src/chroot_utils.sh && $1"

    chroot "$PLX" /bin/bash -c "$CMD"
)}

#pre-download these as no wget in chroot env.
download_file "https://ftp.gnu.org/gnu/gettext/gettext-0.21.tar.xz"
download_file "https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.xz"
download_file "https://www.cpan.org/src/5.0/perl-5.34.0.tar.xz"
download_file "https://www.python.org/ftp/python/3.10.2/Python-3.10.2.tar.xz"
download_file "https://ftp.gnu.org/gnu/texinfo/texinfo-6.8.tar.xz"
download_file "https://www.kernel.org/pub/linux/utils/util-linux/v2.37/util-linux-2.37.4.tar.xz"
download_file "https://zlib.net/zlib-1.2.12.tar.xz"
download_file "http://pyyaml.org/download/pyyaml/PyYAML-5.3.1.tar.gz"
download_file "https://github.com/Mic92/iana-etc/releases/download/20220207/iana-etc-20220207.tar.gz"

do_chroot_build "init_config"
do_chroot_build "build_libstdcpp_p2"
do_chroot_build "build_cross_gettext"
do_chroot_build "build_cross_bison"
do_chroot_build "build_cross_perl"
do_chroot_build "build_cross_python"
do_chroot_build "build_cross_texinfo"
do_chroot_build "build_cross_util_linux"
do_chroot_build "build_pyyaml"

#At this point, the cross env is complete.  Now start building packages.
#First build things so we can get wget

create_package() {( set -e
    if is_installed "pck_$1" ; then
        echo "pck_$1 already packaged"
        return 0
    fi

    do_chroot_build "python3 /build/scripts/build.py $1 /build"

    set_installed "pck_$1"
)}

mkdir -p $PLX/build/bin
cp -r packages/* $PLX/build/

if ! is_installed "precache" ; then
    for f in $(cat $CURDIR/precache-packages)
    do
        download_file "$f"
    done;

    set_installed "precache"
else
    echo "Precache installed"
fi
#pre-download files since no wget yet


create_package "man-pages"
create_package "iana-etc"
create_package "glibc"
create_package "zlib"
create_package "bzip2"
create_package "xz"
create_package "zstd"
create_package "file"
create_package "readline"
create_package "m4"
create_package "bc"
create_package "flex"
create_package "tcl"
create_package "expect"
create_package "dejagnu"
create_package "binutils"
create_package "gmp"
create_package "mpfr"
create_package "mpc"
create_package "attr"
create_package "acl"
create_package "libcap"
create_package "shadow"
create_package "gcc"
create_package "pkg-config"
create_package "ncurses"
create_package "sed"
create_package "psmisc"
create_package "gettext"
create_package "bison"
create_package "grep"
create_package "bash"
create_package "libtool"
create_package "gdbm"
create_package "gperf"
create_package "expat"
create_package "inetutils"
create_package "less"
create_package "perl"
create_package "XML-Parser"
create_package "intltool"
create_package "autoconf"
create_package "automake"
create_package "openssl"
create_package "libtasn1"
create_package "kmod"
create_package "libelf"
create_package "libffi"
create_package "p11-kit"
create_package "make-ca"
create_package "wget"
create_package "python"
create_package "ninja"
create_package "meson"
create_package "coreutils"
create_package "check"
create_package "diffutils"
create_package "gawk"
create_package "findutils"
create_package "groff"
create_package "grub"
create_package "gzip"
create_package "iproute2"
create_package "kbd"
create_package "libpipeline"
create_package "make"
create_package "patch"
create_package "tar"
create_package "texinfo"
create_package "vim"
create_package "markupsafe"
create_package "jinja2"
create_package "systemd"
create_package "dbus"
create_package "man-db"
create_package "procps-ng"
create_package "util-linux"
create_package "e2fsprogs"

do_chroot_build "finalize"

do_chroot_build "inst_base"

create_package "linux"

do_chroot_build "config_shell"

create_package "pam"
create_package "libcap-pam"
create_package "shadow-pam"
create_package "pcre"
create_package "libxml2"
create_package "docbook-xsl-nons"
create_package "unzip"
create_package "sgml-common"
create_package "docbook-xml"
create_package "libxslt"
create_package "glib"
create_package "gobject-introspection"
create_package "which"
create_package "autoconf2"
create_package "libuv"
create_package "curl"
create_package "libarchive"
create_package "nghttp2"
create_package "cmake"
create_package "llvm"
create_package "icu"
create_package "libssh2"
create_package "rustc"
create_package "mozjs"
create_package "polkit"
create_package "systemd-pam"
create_package "sudo"
create_package "xorg-build-env"
create_package "util-macros"
create_package "xorgproto"
create_package "libXau"
create_package "libXdmcp"
create_package "xcb-proto"
create_package "libxcb"
create_package "libpng"
create_package "freetype-nohb"
create_package "graphite2"
create_package "harfbuzz"
create_package "freetype"
create_package "fontconfig"
create_package "xorg-libs"
create_package "libgpg-error"
create_package "libgcrypt"
create_package "libassuan"
create_package "libksba"
create_package "npth"
create_package "nettle"
create_package "libunistring"
create_package "gnutls"
create_package "pinentry"
create_package "gnupg"
create_package "dbus-pam"
create_package "at-spi2-core"
create_package "atk"
create_package "at-spi2-atk"
create_package "nasm"
create_package "yasm"
create_package "libjpeg-turbo"
create_package "itstool"
create_package "xmlto"
create_package "shared-mime-info"
create_package "tiff"
create_package "gdk-pixbuf"
create_package "pixman"
create_package "cairo"
create_package "fribidi"
create_package "graphviz"
create_package "vala"
create_package "pango"
create_package "librsvg"
create_package "libdrm"
create_package "mako"
create_package "libva-nomesa"
create_package "libvdpau"
create_package "wayland"
create_package "wayland-protocols"
create_package "mesa"
create_package "libva"
create_package "libepoxy"
create_package "adwaita-icon-theme"
create_package "hicolor-icon-theme"
create_package "iso-codes"
create_package "xkeyboard-config"
create_package "libsass"
create_package "libxkbcommon"
create_package "sassc"
create_package "gtk+3"
create_package "libsecret"
create_package "accountsservice"
create_package "polkit-gnome"
create_package "gtk+2"
create_package "lxdm"
create_package "gcr"
create_package "gsettings-desktop-schemas"
create_package "sqlite"
create_package "libidn2"
create_package "libpsl"
create_package "glib-networking"
create_package "libsoup"
create_package "rest"
create_package "totem-pl-parser"
create_package "pcre2"
create_package "vte"
create_package "yelp-xsl"
create_package "dbus-glib"
create_package "GConf"
create_package "json-glib"
create_package "geocode-glib"
create_package "graphene"
create_package "pycairo"
create_package "pygobject"
create_package "gstreamer"
create_package "alsa-lib"
create_package "cdparanoia-III"
create_package "libgudev"
create_package "libogg"
create_package "libvorbis"
create_package "libtheora"
create_package "gst-plugins-base"
create_package "libdvdread"
create_package "libdvdnav"
create_package "soundtouch"
create_package "gst-plugins-bad"
create_package "flac"
create_package "lame"
create_package "libvpx"
create_package "mpg123"
create_package "gst-plugins-good"
create_package "gtk+4"
create_package "gjs"
create_package "gnome-autoar"
create_package "libseccomp"
create_package "bubblewrap"
create_package "gnome-desktop"
create_package "gnome-menus"
create_package "gnome-video-effects"
create_package "libwebp"
create_package "ruby"
create_package "libwpe"
create_package "wpebackend-fdo"
create_package "lcms2"
create_package "enchant"
create_package "openjpeg"
create_package "libglade"
create_package "libdaemon"

create_package "jasper"
create_package "libmng"
create_package "xcb-util-image"
create_package "xcb-util-renderutil"
create_package "xcb-util-wm"
create_package "xcb-util-cursor"
create_package "xcb-util-keysyms"
create_package "qt"
create_package "avahi"
create_package "libmbim"
create_package "libqmi"
create_package "modemmanager"
create_package "libnotify"

create_package "geoclue"
create_package "webkitgtk"
create_package "gnome-online-accounts"
create_package "grilo"
create_package "glu"
create_package "libevdev"
create_package "mtdev"
create_package "libinput"
create_package "cogl"
create_package "xcb-util"
create_package "clutter"
create_package "clutter-gtk"
create_package "libchamplain"
create_package "libgee"
create_package "libgtop"
create_package "libgweather"
create_package "libpeas"
create_package "startup-notification"
create_package "libwnck"
create_package "tracker"
create_package "libcanberra"
create_package "libcddb"
create_package "libcdio"
create_package "libcdio-paranoia"
create_package "libdiscid"
create_package "libdvdcss"
create_package "gsound"
create_package "dconf"
create_package "dconf-editor"
create_package "gnome-backgrounds"
create_package "swig"
create_package "libusb"
create_package "libatasmart"
create_package "pygments"
create_package "libbytesize"
create_package "yaml"
create_package "libaio"
create_package "lvm2"
create_package "dosfstools"
create_package "parted"
create_package "json-c"
create_package "popt"
create_package "cryptsetup"
create_package "gpgme"
create_package "nspr"
create_package "nss"
create_package "volume_key"
create_package "libblockdev"
create_package "lzo"
create_package "asciidoc"
create_package "btrfs-progs"
create_package "gptfdisk"
create_package "mdadm"
create_package "inih"
create_package "userspace-rcu"
create_package "xfsprogs"
create_package "udisks"
create_package "openssh"
create_package "gvfs"
create_package "exiv2"
create_package "gexiv2"
create_package "boost"
create_package "exempi"
create_package "libass"
create_package "fdk-aac"
create_package "opus"
create_package "x264"
create_package "x265"
create_package "sdl2"
create_package "ffmpeg"
create_package "giflib"
create_package "libexif"
create_package "libgrss"
create_package "libgxps"
create_package "poppler"
create_package "tracker-miners"
create_package "libhandy"
create_package "desktop-file-utils"
create_package "libportal"
create_package "nautilus"
create_package "zenity"
create_package "gnome-bluetooth"
create_package "gnome-keyring"
create_package "libgusb"
create_package "colord"
create_package "libwacom"
create_package "speex"
create_package "speexdsp"
create_package "libsndfile"
create_package "pulseaudio"
create_package "upower"
create_package "lynx"
create_package "xdg-utils"
create_package "cups"

create_package "libndp"
create_package "jansson"
create_package "dhcp-client"
create_package "iptables"
create_package "slang"
create_package "newt"
create_package "libnl"
create_package "wpa_supplicant"
create_package "networkmanager"


create_package "gnome-settings-daemon"
create_package "libxcvt"
create_package "v4l-utils"
create_package "libdazzle"
create_package "sysprof"
create_package "font-util"
create_package "libtirpc"
create_package "xwayland"
create_package "sbc"
create_package "pipewire"

create_package "cracklib"
create_package "colord"
create_package "libpwquality"
create_package "clutter-gst"
create_package "cheese"
create_package "ibus"
create_package "krb5"
create_package "libnma"
create_package "colord-gtk"

create_package "lmdb"
create_package "rpcsvc-proto"
create_package "parse-yapp"
create_package "libgdata"
create_package "samba"

create_package "gnome-control-center"
create_package "mutter"
create_package "libical"
create_package "evolution-data-server"
create_package "gnome-shell"
create_package "gnome-shell-extensions"
create_package "gnome-session"
create_package "gdm"
create_package "xorg-server"
create_package ""
create_package ""
create_package ""
create_package ""
create_package ""
create_package ""
create_package ""
create_package ""
create_package ""



)

$CURDIR/uvmount.sh
