#!/usr/bin/python3

import sys
import os
from subprocess import Popen, PIPE, DEVNULL
import shutil

depstart = 4

if sys.argv[1] == '-u':
	depstart = 3
	fn = sys.argv[2]
	pck = os.path.basename(fn).rsplit('.t')[0]
	ver = pck.rsplit('-')[-1]
	pck = pck.rsplit('-' + ver)[0]
else:
	pck = sys.argv[1]
	ver = sys.argv[2]
	fn = sys.argv[3]

base_repo = os.environ['PLX_REPO']
l0 = pck[0]
filename = os.path.basename(fn)

repo_path = base_repo + l0 + '/' + pck

if not os.path.exists(base_repo + l0):
	os.mkdir(base_repo + l0)

if os.path.exists(repo_path):
	print('Already exists!')
	sys.exit(-1)

os.mkdir(repo_path)

with open(repo_path + '/.pck', 'w') as out:
	out.write('name: ' + pck + '\n')
	out.write('version: ' + ver + '\n')
	out.write('repo: core\n')
	out.write('source: ' + fn + '\n')
	out.write('deps: [\n')

	for n in range(depstart,len(sys.argv)):
		out.write('  \'' + sys.argv[n] + '\',\n')

	out.write(']\n')
	out.write('mkdeps: []\n')
	out.write('extras: [\n]\n')

print('Created: ' + repo_path + '/.pck')

with open(repo_path + '/.build', 'w') as out:
    out.write('tar -xf $filename\n')
    out.write('pckname=${filename%.t*}\n')
    out.write('cd ' + pck + '-' + ver + ' || cd $pckname\n\n')
    out.write('./configure $XORG_CONFIG\n\n')
    out.write('make\nmake DESTDIR=$pckdir install\n\n')

print('Created: ' + repo_path + '/.build')

p = Popen('vim ' + repo_path + '/.build', shell=True)
p.wait()

